on: 
  push:
  pull_request:
  schedule:
  - cron: '0 19 * * *'
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15, 1.14, 1.13]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Code
      run: go build main.go
    - name: Test
      run: go test ./... -v